<?php

declare(strict_types=1);

namespace Calien\PhpUnitDeprecationCauser;

/**
 * Maps a file a framework generated from other files, such as a concatenated cache file, back to the file the code
 * at a line came from. Framework integrations pass their mappers to {@see DeprecationCauserRegistrar}.
 */
interface GeneratedFileMapper
{
    /**
     * Returns null when the file is not generated by this mapper's framework.
     *
     * @return non-empty-string|null
     */
    public function sourceFile(string $file, int $line): ?string;
}
